defaults:
  - default
  - _self_

# Override from `default` config
id: PyFlyt

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.pyflyt.PyFlytGymWrapper
  id: ${env.id}
  render_mode: rgb_array
